name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build 1
        run: |
          echo "Running build 1"
          # Your build commands here

  build-2:
    needs: build-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build 2
        run: |
          echo "Running build 2"
          # Your build commands here
