name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          mvn clean package

      - name: Deploy to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name:single-module
          path: target/single-module-project.jar

  deploy-to-production:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # deployment script
